name: RustAction

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt_build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fmt
      run: cargo fmt -- --check
    - name: Build
      run: cargo build
